---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/{enterprise_subdomain}/v1/petitions/create":
    post:
      summary: Create a new petition
      tags:
      - Community API V1 Petitions
      description: Allow to users create petitions
      parameters:
      - name: enterprise_subdomain
        in: path
        description: this subdomain of enterprise create in creations tenant
        required: true
        schema:
          type: string
      - name: lang
        in: query
        description: is optional by default is "es"
        schema:
          type: string
      - name: Authorization
        in: header
        required: true
      responses:
        '200':
          description: success!!!
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: true
                  data:
                    type: object
                    properties:
                      ticket:
                        type: string
        '404':
          description: error category, group_role not found!!!
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: false
                  message:
                    type: string
        '403':
          description: error not logged!!!
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: false
                  message:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                petition:
                  type: object
                  properties:
                    title:
                      type: string
                    message:
                      type: string
                    category_petition_id:
                      type: integer
                    group_role_id:
                      type: integer
  "/{enterprise_subdomain}/v1/users/forgot_password":
    post:
      summary: Create a new request for change password
      tags:
      - Community API V1 Users
      description: Allow to users do change to password
      parameters:
      - name: enterprise_subdomain
        in: path
        description: this subdomain of enterprise create in creations tenant
        required: true
        schema:
          type: string
      - name: lang
        in: query
        description: is optional by default is "es"
        schema:
          type: string
      responses:
        '200':
          description: success!!!
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: true
                  message:
                    type: string
        '422':
          description: error email is empty!!!
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: false
                  message:
                    type: string
        '404':
          description: error user not found!!!
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: false
                  message:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                forgot_password:
                  type: object
                  properties:
                    email:
                      type: string
  "/{enterprise_subdomain}/v1/users/profile/show":
    get:
      summary: Find the profile of current user
      tags:
      - Community API V1 Users
      description: Allow see the user's data logged
      parameters:
      - name: Authorization
        in: header
        required: true
      - name: enterprise_subdomain
        in: path
        description: this subdomain of enterprise create in creations tenant
        required: true
        schema:
          type: string
      - name: lang
        in: query
        description: is optional by default is "es"
        schema:
          type: string
      responses:
        '200':
          description: success!!!
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: true
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      lastname:
                        type: string
                      email:
                        type: string
                      address:
                        type: string
                        nullable: true
                      identifier:
                        type: string
                      phone:
                        type: string
                        nullable: true
        '403':
          description: error user not valid!!!
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: false
                  message:
                    type: string
  "/{enterprise_subdomain}/v1/users/sign_in":
    post:
      summary: Create login by user
      tags:
      - Community API V1 Users
      description: Allow to users enter to api through of the email and password
      parameters:
      - name: enterprise_subdomain
        in: path
        description: this subdomain of enterprise create in creations tenant
        required: true
        schema:
          type: string
      - name: lang
        in: query
        description: is optional by default is "es"
        schema:
          type: string
      responses:
        '200':
          description: success!!!
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: true
                  data:
                    type: object
                    properties:
                      jwt:
                        type: string
        '403':
          description: error password or user is not active!!!
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: false
                  message:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sign_in:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
